/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stateChangeSol from "./StateChange.sol";
export type { stateChangeSol };
export type { HelloWorld } from "./HelloWorld";
export * as factories from "./factories";
export { HelloWorld__factory } from "./factories/HelloWorld__factory";
export type { CheckMarksCMS } from "./StateChange.sol/CheckMarksCMS";
export { CheckMarksCMS__factory } from "./factories/StateChange.sol/CheckMarksCMS__factory";
